#Script for comparing two sets of output (perhaps generated by different encodings, or implementations)
#Compares returned values (SAT/UNSAT) and gives relative time
#Usage:
#  create 2 directories and put the two sets of output files in each (the names of files must agree and end with "out")
#  cd into the first of the directories
#  run: script-output.sh path_to_the_other_directory

#go through all out files in pwd
for J in *out; do

 #get the two return values
 A=`grep "Formula is" $1/$J | grep -o "[A-Z]*SAT"`;
 B=`grep "Formula is" $J | grep -o "[A-Z]*SAT"`;

 #print file name we are comparing
 echo "$J:"

 #say if values agree
 if [ "$A" != "$B" ]; then
   echo " - values differ ($A vs $B)";
 else
   echo " - values agree";
 fi;

 #get the two output times
 TA=`grep "Solving Time" $1/$J | grep -o "[0-9]*[.][0-9]*"`
 TB=`grep "Solving Time" $J | grep -o "[0-9]*[.][0-9]*"`
 
 #compare the output times
 DIFF=`echo "$TB/$TA" | bc -l`

 #print out the comparison of output times
 echo " - relative difference is $DIFF";
done
