/*************************************************************/
/* Automatically generated by './mkconfig.sh': do note edit! */
/*************************************************************/
#define LGL_OS "Linux dhriti 3.19.0-25-generic x86_64"
#define LGL_COMPILED "Wed Jun 22 10:27:32 IST 2016"
#define LGL_RELEASED "Wed Oct 16 17:03:36 CEST 2013"
#define LGL_VERSION "ats"
#define LGL_ID "57807c8f410a9e676816984a0ad0c410e485bcae"
