#!/bin/sh

die () {
   echo "*** mkconfig.sh: $*" 1>&2
   exit 1
}

[ -f makefile ] || die "can not find 'makefile'"

cat<<EOF
/*************************************************************/
/* Automatically generated by './mkconfig.sh': do note edit! */
/*************************************************************/
EOF

echo "#define LGL_OS \"`uname -srmn`\""
echo "#define LGL_COMPILED \"`date`\""
cat<<EOF
#define LGL_RELEASED "Wed Oct 16 17:03:36 CEST 2013"
#define LGL_VERSION "ats"
#define LGL_ID "57807c8f410a9e676816984a0ad0c410e485bcae"
EOF
